In [1]:
import numpy as np

In [2]:
class BackPropagation(object):
    def __init__(self):
        self.no_input = 3
        self.no_hidden = 2
        self.no_output = 2
        
        self.X = np.array([1, 0, 1], dtype = float)
        self.T = np.array(([1, 0]), dtype = float)
        
        "self.W_ih = np.ndarray(shape=(self.no_hidden, self.no_input), dtype=float)"
        self.W_ih = np.array(([0.2, 0.4, -0.5],
                             [-0.3, 0.1, 0.2]), dtype = float)
        "self.W_oh = np.ndarray(shape=(self.no_output, self.no_hidden), dtype=float)"
        self.W_oh = np.array(([-0.3, -0.2],
                             [0.4, 0.6]), dtype = float)
        
        self.hidden_bias = np.array([-0.4, 0.2], dtype = float)
        self.output_bias = np.array([0.1, 0.2], dtype = float)
        
        self.I_hidden = np.zeros(self.no_hidden, dtype = float)
        self.O_hidden = np.zeros(self.no_hidden, dtype = float)
        
        self.I_output = np.zeros(self.no_output, dtype = float)
        self.O_output = np.zeros(self.no_output, dtype = float)
        
        self.Err_output = np.zeros(self.no_output, dtype = float)
        self.Err_hidden = np.zeros(self.no_hidden, dtype = float)
        
    def sigmoid(self, Ij):
        return (1/(1+(np.exp(-Ij))))
    
    def backpropagation(self):
        for epoch in range(15):
            print("Epoch-" , epoch)
            print("---------------------")
            "for each hidden layer calculate the input and output to the hidden layer"
            for i in range(self.no_hidden):
                for j in range(self.no_input):
                    self.I_hidden[i] = self.I_hidden[i] + (self.W_ih[i, j] * self.X[j])
                self.I_hidden[i] = self.I_hidden[i] + self.hidden_bias[i]
                self.O_hidden[i] = self.sigmoid(self.I_hidden[i])

            print("Hidden Layer(Input)" , self.I_hidden)
            print("")
            print("Hidden Layer(Output)", self.O_hidden)
            print("")
            
            "for each output layer calculate the input and output"
            for i in range(self.no_output):
                for j in range(self.no_hidden):
                    self.I_output[i] = self.I_output[i] + (self.W_oh[i, j] * self.O_hidden[j])
                self.I_output[i] = self.I_output[i] + self.output_bias[i]
                self.O_output[i] = self.sigmoid(self.I_output[i])

            print("Output Layer(Input)" , self.I_output)
            print("")
            print("Output Layer(Output)", self.O_output)
            print("")

            "for each output layer calculate the Error"
            for i in range(self.no_output):
                self.Err_output[i] = self.O_output[i] * (1 - self.O_output[i]) * (self.T[i] - self.O_output[i])
            print("Err-Output:" , self.Err_output)

            "for each hidden layer calculate the Error"
            for i in range(self.no_hidden):
                sum = 0.0
                for j in range(self.no_output):
                    sum = sum + (self.Err_output[j] * self.W_oh[j, i])
                self.Err_hidden[i] = self.O_hidden[i] * (1 - self.O_hidden[i]) * sum
            print("Err-hidden" , self.Err_hidden)
            print("")

            "update weights associated to hidden to output layer"
            for i in range(self.no_hidden):
                for j in range(self.no_output):
                    self.W_oh[j, i] = self.W_oh[j, i] + (self.Err_output[j] * self.O_hidden[i])
            
            print("Updated Weight(From Hidden To Output Layer): ")
            print(self.W_oh)
            print("")

            "update weights associated with the hidden layer"
            for i in range(self.no_hidden):
                self.hidden_bias[i] = self.hidden_bias[i] + self.Err_hidden[i]

            print("Updated bias at hidden layer:")
            print(self.hidden_bias)
            print("")

            "update weights associated to input to hidden layer"
            for i in range(self.no_hidden):
                for j in range(self.no_input):
                    self.W_ih[i, j] = self.W_ih[i, j] + (self.Err_hidden[i] * self.X[j])
            print("Updated Weights (From Input to Hidden layer):")
            print(self.W_ih)
            print("")

            "update biases at output layer"
            for i in range(self.no_output):
                    self.output_bias[i] = self.output_bias[i] * self.Err_output[i]
            print("Updated bias at the output layer:")
            print(self.output_bias)
            print("")

bp = BackPropagation()
bp.backpropagation()
        

Epoch- 0
---------------------
Hidden Layer(Input) [-0.7  0.1]

Hidden Layer(Output) [0.33181223 0.52497919]

Output Layer(Input) [-0.10453951  0.6477124 ]

Output Layer(Output) [0.4738889  0.65649477]

Err-Output: [ 0.13116908 -0.14804573]
Err-hidden [-0.02185402 -0.02869352]

Updated Weight(From Hidden To Output Layer): 
[[-0.2564765  -0.13113896]
 [ 0.35087662  0.52227907]]

Updated bias at hidden layer:
[-0.42185402  0.17130648]

Updated Weights (From Input to Hidden layer):
[[ 0.17814598  0.4        -0.52185402]
 [-0.32869352  0.1         0.17130648]]

Updated bias at the output layer:
[ 0.01311691 -0.02960915]

Epoch- 1
---------------------
Hidden Layer(Input) [-1.46556206  0.11391944]

Hidden Layer(Output) [0.1876181 0.5284491]

Output Layer(Input) [-0.2088425   0.95993196]

Output Layer(Output) [0.44797832 0.72310818]

Err-Output: [ 0.13651151 -0.1447827 ]
Err-hidden [-0.01307939 -0.02330405]

Updated Weight(From Hidden To Output Layer): 
[[-0.23086447 -0.05899958]
 [ 0.323712

Hidden Layer(Input) [-11.47524341  -1.40236207]

Hidden Layer(Output) [1.03839025e-05 1.97441554e-01]

Output Layer(Input) [0.50049785 1.9363484 ]

Output Layer(Output) [0.62257632 0.87395043]

Err-Output: [ 0.08868515 -0.09627532]
Err-hidden [-4.92390369e-07  5.72310155e-03]

Updated Weight(From Hidden To Output Layer): 
[[-0.20723838  0.44330594]
 [ 0.30163465 -0.00192872]]

Updated bias at hidden layer:
[-0.44639161  0.14664521]

Updated Weights (From Input to Hidden layer):
[[ 0.15360839  0.4        -0.54639161]
 [-0.35335479  0.1         0.14664521]]

Updated bias at the output layer:
[1.35223319e-14 9.39669725e-15]

Epoch- 14
---------------------
Hidden Layer(Input) [-12.31441825  -1.46242645]

Hidden Layer(Output) [4.48656701e-06 1.88096487e-01]

Output Layer(Input) [0.58388121 1.93598697]

Output Layer(Output) [0.64195998 0.87391061]

Err-Output: [ 0.08229455 -0.09629696]
Err-hidden [-2.06834700e-07  5.59970515e-03]

Updated Weight(From Hidden To Output Layer): 
[[-0.20723801 